name: 'Canary Release'

on:
  push:
    branches:
      - canary

# Releases a canary tagged version of the packages
jobs:
  canary_release:
    name: canary version and publish
    env:
      CI: true
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo and setup pnpm
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.0
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          commit: 'canary-release'
          title: 'Canary Release'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.23.0
        id: slack
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
