name: 'Starter Split and Changesets'

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    name: version and publish
    env:
      CI: true
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo and setup pnpm
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.0
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'Update versions'
          title: 'Update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action result: ${{ job.status }}\n${{ github.ref }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action result: ${{ job.status }}\n${{ github.ref }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  packages_split:
    # only run this job after release have finished
    needs: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        include:
          # next-drupal-starter
          - local_path: 'starters/next-drupal-starter-generated'
            split_repository: 'next-drupal-starter'
            generator_cmd:
              "next-drupal next-drupal-umami-addon --appName
              @pantheon-systems/next-drupal-starter --cmsEndpoint '' --noInstall
              --tailwindcss --force --silent"
          # gatsby-wordpress-starter
          - local_path: 'starters/gatsby-wordpress-starter-generated'
            split_repository: 'gatsby-wordpress-starter'
            generator_cmd:
              "gatsby-wp --appName @pantheon-systems/gatsby-wordpress-starter
              --cmsEndpoint '' --noInstall --tailwindcss --force --silent"
          # next-wordpress-starter
          - local_path: 'starters/next-wordpress-starter-generated'
            split_repository: 'next-wordpress-starter'
            generator_cmd:
              "next-wp --appName @pantheon-systems/next-wordpress-starter
              --cmsEndpoint '' --noInstall --tailwindcss --force --silent"

            # docs site
          - local_path: 'web'
            split_repository: 'decoupled-kit-docs'
            generator_cmd: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        if: ${{ matrix.generator_cmd != '' }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
        # install canary version of the CLI
        # run the command to generate the starter in the matrix.local_path directory
      - name: Generate starter
        if: ${{ matrix.generator_cmd != '' }}
        run: |
          npm i --global create-pantheon-decoupled-kit
          create-pantheon-decoupled-kit ${{ matrix.generator_cmd }} --outDir ./${{ matrix.local_path }}

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'danharrin/monorepo-split-github-action@v2.3.0'
        with:
          # ↓ split <local_path> directory
          package_directory: '${{ matrix.local_path }}'

          # ↓ into https://github.com/org/split_repository repository
          repository_organization: 'pantheon-systems'
          repository_name: '${{ matrix.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: 'pantheon-decoupled-service-user'
          user_email: 'decoupled-service-user@pantheon.io'

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'danharrin/monorepo-split-github-action@v2.3.0'
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: '${{ matrix.local_path }}'

          repository_organization: 'pantheon-systems'
          repository_name: '${{ matrix.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: 'pantheon-decoupled-service-user'
          user_email: 'decoupled-service-user@pantheon.io'
